name: Render with MarkdownBlogger

on:
  push:
    branches: [gh-pages]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: cemreefe/MarkdownBlogger

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Install Python modules
        run: |
            sudo apt-get update
            sudo apt-get install -y libxml2-dev libxslt-dev
            pip3 install markdown jinja2

      - name: Run Python script
        run: python3 render.py source 'MarkdownBlogger Test'
