name: Render with MarkdownBlogger

on:
  push:
    branches: [ gh-pages ]

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install markdown==3.3.4 jinja2
    - name: Clone MarkdownBlogger
      run: git clone https://github.com/cemreefe/MarkdownBlogger
    - name: Run MarkdownBlogger
      run: |
        cd MarkdownBlogger
        python3 render.py ../source 'TestWebsite - MarkdownBlogger'
        echo "---"
        ls
        echo "---"
        ls ..
        echo "---"
        
    - name: Commit changes
      run: |
        git config --global user.name 'Cemre'
        git config --global user.email 'cemreefe@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
        git add -A 
        git commit -m "Automated rendering"
        git push
