name: Render with MarkdownBlogger

on:
  push:
    branches: 
    - source

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install markdown==3.3.4 jinja2
    - name: Clone MarkdownBlogger
      run: git clone https://github.com/cemreefe/MarkdownBlogger
    - name: Run MarkdownBlogger
      run: |
        cd MarkdownBlogger
        python3 render.py -i ../source -o ../output -t 'TestWebsite' -th themes/custom.css --root MarkdownBlogger-Test
    - name: Cleanup repo
      run: |
        rm -r MarkdownBlogger
    - name: Clone github pages branch and clean its contents
      run: |
        cd ..
        mkdir ghp
        cd ghp
        git clone -b gh-pages https://github.com/cemreefe/MarkdownBlogger-Test
        cd MarkdownBlogger-Test
        git rm -r '*'
    - name: Move new output into github pages branch
      run: |
        mv output/* ../ghp/MarkdownBlogger-Test/
        
    - name: Commit changes
      run: |
        cd ../ghp/MarkdownBlogger-Test/
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.AUTO_RENDER_PAT }}@github.com/$GITHUB_REPOSITORY
        git add -A 
        git commit -m "Automatically rendered on `date +'%Y-%m-%d %H:%M:%S'`"
        git push
